;;; pink-bliss-uwu-theme-autoloads.el --- automatically extracted autoloads (do not edit)   -*- lexical-binding: t -*-
;; Generated by the `loaddefs-generate' function.

;; This file is part of GNU Emacs.

;;; Code:

(add-to-list 'load-path (or (and load-file-name (directory-file-name (file-name-directory load-file-name))) (car load-path)))



;;; Generated autoloads from pink-bliss-uwu-theme.el

(when load-file-name (add-to-list 'custom-theme-load-path (file-name-directory load-file-name)))
(register-definition-prefixes "pink-bliss-uwu-theme" '("pink-bliss-"))

;;; End of scraped data

(provide 'pink-bliss-uwu-theme-autoloads)

;; Local Variables:
;; version-control: never
;; no-byte-compile: t
;; no-update-autoloads: t
;; no-native-compile: t
;; coding: utf-8-emacs-unix
;; End:

;;; pink-bliss-uwu-theme-autoloads.el ends here
